{% set name = "pydeb" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jornbr/{{ name }}/releases/download/v{{ version }}/{{ name }}.tar.gz
  sha256: e6d64670e33fd3879b17cb4401157322c7fbe14d614521f3a751ba65004ca429

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - pydeb = pydeb.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler("c") }}
  host:
    - python {{ python }}
    - cython
    - pip
    - setuptools
    - setuptools_scm
    - numpy
  run:
    - python

test:
  imports:
    - pydeb
  requires:
    - pip
  commands:
    - pip check
    - pydeb -v
    #- pydeb "Asterias rubens"

about:
  home: https://github.com/jornbr/pydeb
  summary: 'Dynamic Energy Budget models in Python'
  description: |
    pydeb is a Python package for building and analyzing Dynamic Energy Budget
    models. It supports phylogenetic inference of DEB models for new species,
    simulation of growth, reproduction and survival, and Bayesian inference
    with the Adaptive Metropolis algorithm. It is designed for high performance
    and can analyze 100,000 parameter sets in under 2 minutes on most
    workstations.
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jornbr
